spring.application.name=kontrolltoo

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# asenda /webshop kontrolltöös ära
#spring.datasource.url=jdbc:postgresql://localhost:5432/webshop

spring.datasource.username=postgres
spring.datasource.password=root
